#TODO(komposten): Come up with a name that is easy to remember and write.
name: dart_repl
description: A REPL interface for executing dart code directly from the command line.
version: 0.0.1
homepage: https://github.com/komposten
repository: https://www.github.com/komposten/dart_repl
issue_tracker: https://www.github.com/komposten/dart_repl/issues
author: Jakob Hjelm <komposten585@gmail.com>

environment:
  sdk: '>=2.8.0 <3.0.0'

dependencies:
  path: ^1.7.0

dev_dependencies:
  coverage: ^0.14.0
  pedantic: ^1.9.0
  test: ^1.15.0
